FROM docker.io/php:8.2-fpm-alpine

WORKDIR /app

RUN apk upgrade --update --no-check-certificate \
  && apk add ca-certificates --update --no-cache --no-check-certificate \
  && curl -sko /usr/local/share/ca-certificates/CheckpointCA.crt https://raw.githubusercontent.com/dlonghi/containers/main/CheckpointCA.crt \
  && update-ca-certificates \
  && apk add tzdata --update --no-cache \
  && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
  && echo America/Sao_Paulo > /etc/timezone \
  && echo \
  && apk add shadow --update --no-cache \
  && usermod -u 1000 www-data \
  && groupmod -g 1000 www-data \
  && apk del shadow \
  && echo \  
  && apk add --update --no-cache \
    msmtp \
    freetype \
    libjpeg-turbo \
    libpng \
    libwebp \
    libmemcached \
    libpq \
    libzip \
    libxslt \
  && apk add --no-cache $PHPIZE_DEPS --virtual .build-deps \
    git \
    linux-headers \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    zlib-dev \
    libmcrypt-dev \
    libxml2-dev \
    libzip-dev \
    readline-dev \
    libpq-dev \
    pcre-dev \
    libmemcached-dev \
    cyrus-sasl-dev \
    libxslt-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install soap \
  && docker-php-ext-install bcmath \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-install mysqli \
  && docker-php-ext-install pdo_pgsql \
  && docker-php-ext-install zip \
  && docker-php-ext-install opcache \
  && docker-php-ext-install xsl \
  && echo \
  && pecl install uploadprogress \
  && docker-php-ext-enable uploadprogress \
  && pecl install memcached \
  && docker-php-ext-enable memcached \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && echo \
  & mkdir /app/public \
  && echo '<?php echo "<pre>"; print_r(get_defined_vars()); echo "</pre>"; phpinfo(); xdebug_info();' > /app/public/info.php \
  && echo \
  && apk del $PHPIZE_DEPS .build-deps \
  && rm -rf /var/cache/apk/*

COPY . /app
