FROM docker.io/php:8.2-fpm

ENV TZ=America/Sao_Paulo
ARG AMBIENTE=prd

WORKDIR /app

RUN apt-get update \
  && curl -sko /usr/local/share/ca-certificates/CheckpointCA.crt https://raw.githubusercontent.com/dlonghi/containers/main/CheckpointCA.crt \
  && update-ca-certificates \
  && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
  && usermod -u 1000 www-data \
  && groupmod -g 1000 www-data \
  && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    zip \
    unzip \
    libzip-dev \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libpng-dev \
    libmagickwand-dev \
    libpq-dev \
    libmemcached-dev \
    libxslt-dev \
    libbz2-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install soap \
  && docker-php-ext-install bcmath \
  && docker-php-ext-install mysqli \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-install pdo_pgsql \
  && docker-php-ext-install zip \
  && docker-php-ext-install opcache \
  && docker-php-ext-install xsl \
  && docker-php-ext-install bz2 \
  && pecl install imagick \
  && docker-php-ext-enable imagick \
  && pecl install memcached \
  && docker-php-ext-enable memcached \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && echo \
  && mkdir /app/public \
  && echo '<?php echo "<pre>"; print_r(get_defined_vars()); echo "</pre>"; phpinfo(); xdebug_info();' > /app/public/info.php \
  && echo \
  && apt-get purge -y build-essential && apt-get autoremove -y && apt-get clean

RUN if [ ${AMBIENTE} = "dev" ]; then \
  pecl install xdebug \
  && docker-php-ext-enable xdebug \
;fi
