FROM docker.io/nginx:1.27.1

RUN curl -sko /usr/local/share/ca-certificates/CheckpointCA.crt https://raw.githubusercontent.com/dlonghi/containers/main/CheckpointCA.crt \
 && update-ca-certificates \
 && apt-get update && apt-get upgrade -y \
 && apt-get autoremove -y && apt-get clean \
 && ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && echo America/Sao_Paulo > /etc/timezone \
 && mkdir /opt/certs \
 && openssl req -new -x509 -sha512 -nodes -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -subj "/C=BR/ST=DF/L=Brasilia/CN=*.localhost/O=None" -addext "subjectAltName = DNS:localhost, DNS:127.0.0.1" -keyout /opt/certs/server.key -out /opt/certs/server.crt -days 3650 \
 && groupmod -g 12000 nginx \
 && usermod -u 12000 -g 12000 nginx

RUN curl -ko /etc/nginx/nginx.conf https://raw.githubusercontent.com/dlonghi/containers/main/nginx/config/nginx_kube.conf \
 && mkdir -p /app/public \
 && curl -ko /app/public/index.html https://raw.githubusercontent.com/dlonghi/containers/main/assets/index_flying_lights.html \
 && curl -ko /app/public/favicon.ico https://raw.githubusercontent.com/dlonghi/containers/main/assets/favicon_nginx.ico
