FROM docker.io/nginx:1.27.1-alpine

RUN apk upgrade --update --no-cache --no-check-certificate \
 && apk add ca-certificates --update --no-cache --no-check-certificate \
 && curl -sko /usr/local/share/ca-certificates/CheckpointCA.crt https://raw.githubusercontent.com/dlonghi/containers/main/CheckpointCA.crt \
 && update-ca-certificates \
 && apk add tzdata --update --no-cache \
 && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
 && echo America/Sao_Paulo > /etc/timezone \
 && mkdir /opt/certs \
 && apk add openssl --update --no-cache \
 && openssl req -new -x509 -sha512 -nodes -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -subj "/C=BR/ST=DF/L=Brasilia/CN=*.localhost/O=SelfSignedCert" -addext "subjectAltName = DNS:localhost, DNS:127.0.0.1" -keyout /opt/certs/server.key -out /opt/certs/server.crt -days 3650 \
 && chmod 600 /opt/certs/server.key \
 && apk del openssl \
 && apk add shadow --update --no-cache \
 && groupmod -g 12000 nginx \
 && usermod -u 12000 -g 12000 nginx \
 && apk del shadow \
 && rm -rf /var/cache/apk/*

RUN curl -ko /etc/nginx/nginx.conf https://raw.githubusercontent.com/dlonghi/containers/main/nginx/config/nginx_kube.conf \
 && mkdir -p /app/public \
 && curl -ko /app/public/index.html https://gist.githubusercontent.com/dlonghi/b53959ad2981d033e8c60f3dc6281c1b/raw/index_gray.html \
 && curl -ko /app/public/favicon.ico https://raw.githubusercontent.com/dlonghi/containers/main/assets/favicon_nginx.ico
